name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout version
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install

      - name: Start docker container
        uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker/test/docker-compose.yml"

      - name: Run Tests
        run: |
          make migration-up
          make test-full
